name: F1XL Notifications

on:
  schedule:
    - cron: '0 18-23 * * 3,4,5,6,0'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run notifications bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_TICKETS_CHANNEL_ID: ${{ secrets.DISCORD_TICKETS_CHANNEL_ID }}
          DISCORD_BANS_CHANNEL_ID: ${{ secrets.DISCORD_BANS_CHANNEL_ID }}
          DISCORD_DIV1_COORDINATOR_ROLE: ${{ secrets.DISCORD_DIV1_COORDINATOR_ROLE }}
          DISCORD_DIV2_COORDINATOR_ROLE: ${{ secrets.DISCORD_DIV2_COORDINATOR_ROLE }}
          DISCORD_DIV3_COORDINATOR_ROLE: ${{ secrets.DISCORD_DIV3_COORDINATOR_ROLE }}
          DISCORD_DIV4_COORDINATOR_ROLE: ${{ secrets.DISCORD_DIV4_COORDINATOR_ROLE }}
          DISCORD_DIV5_COORDINATOR_ROLE: ${{ secrets.DISCORD_DIV5_COORDINATOR_ROLE }}
          DISCORD_DIV6_COORDINATOR_ROLE: ${{ secrets.DISCORD_DIV6_COORDINATOR_ROLE }}
          DISCORD_DIV7_COORDINATOR_ROLE: ${{ secrets.DISCORD_DIV7_COORDINATOR_ROLE }}
          DISCORD_DIV8_COORDINATOR_ROLE: ${{ secrets.DISCORD_DIV8_COORDINATOR_ROLE }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: node bot/notifications.js
